apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-lab13
spec:
  replicas: 6
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: ek00/httpd1:newer
          ports:
            - containerPort: 80
